### ISSUE TITLE
Server'ı çalıştırırken hata alıyorum

### ISSUE THREAD

**Issue by hkulekci** [alpcanaydin/github-stats-for-turkey#8]
Merhaba, server'ı çalıştırırken aşağıdaki gibi bir hata alıyorum. Node sürümü de uygun gibi görünüyor.

```
⋊> /V/w/g/g/server on master ⨯ node app.js                                                                  11:29:36
/Volumes/webroot/github/github-stats-for-turkey/server/controller/initial.js:3
module.exports = async (req, res) => {
                       ^
SyntaxError: Unexpected token (
    at Object.exports.runInThisContext (vm.js:78:16)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Volumes/webroot/github/github-stats-for-turkey/server/routes.js:6:21)
    at Module._compile (module.js:571:32)
⋊> /V/w/g/g/server on master ⨯ node -v                                                                      11:30:38
v7.4.0
```

**Comment by alpcanaydin** [comment]
merhaba, node 7.7.4'te geliştirdim ben en az bu versiyonda deneyebilir misiniz?

**Comment by hkulekci** [comment]
`7.8` ile çalıştı.
